services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    env_file:
      - .env
    volumes:
      - ./backend/media:/app/media
      - ./backend/staticfiles:/app/staticfiles

  frontend:
    build: ./frontend
    restart: always

volumes:
  postgres_data: