# Generated by Django 6.0.5 on 2026-06-03 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BathCup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='аренда купели')),
            ],
            options={
                'verbose_name': 'Стоимость аренды купели',
            },
        ),
        migrations.CreateModel(
            name='BathOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Дополнительные услуги')),
                ('modal', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Дополнительные банные услуги',
            },
        ),
        migrations.CreateModel(
            name='BathProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название банной программы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание программы')),
                ('list', models.TextField(blank=True, null=True, verbose_name='Перечисление, что включает в себя программа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступность программы')),
                ('duration', models.PositiveIntegerField(default=2, verbose_name='Продолжительность программы (часы)')),
            ],
            options={
                'verbose_name': 'Программы парения',
            },
        ),
        migrations.CreateModel(
            name='BathTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='аренда бани по времени')),
            ],
            options={
                'verbose_name': 'Стоимость аренды бани',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('title', models.CharField(blank=True, max_length=120, null=True, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Галерея',
            },
        ),
        migrations.CreateModel(
            name='HomePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='опции аренды дома')),
            ],
            options={
                'verbose_name': 'Опции аренды дома',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=255, unique=True)),
                ('avatar', models.ImageField(default='avatars/default_avatar.png', upload_to='avatars')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(max_length=120, verbose_name='Номер телефона')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтверждена'), ('canceled', 'Отменена'), ('completed', 'Завершена')], default='new', max_length=10, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='BathBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('duration', models.PositiveSmallIntegerField(choices=[(2, '2 часа'), (3, '3 часа'), (4, '4 часа')], verbose_name='Продолжительность бани')),
                ('bath_tub', models.BooleanField(default=False, verbose_name='Купель')),
                ('bath_tub_filling', models.BooleanField(blank=True, default=False, max_length=120, verbose_name='Наполнение')),
                ('steaming', models.BooleanField(default=False)),
                ('whisk', models.CharField(blank=True, choices=[('oak', 'Дуб'), ('fir', 'Пихта'), ('birch', 'Береза')], max_length=20, null=True)),
                ('steam_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bathPrograms', to='app.bathprogram', verbose_name='Программы парения')),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bathBookings', to='app.booking', verbose_name='Бронирование')),
            ],
            options={
                'verbose_name': 'Заявки на бронирование бани',
            },
        ),
        migrations.CreateModel(
            name='HomeBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guests_count', models.PositiveIntegerField(verbose_name='Количество человек')),
                ('extra_place', models.BooleanField(default=False, verbose_name='Дополнительное место')),
                ('with_pet', models.BooleanField(default=False, verbose_name='С животными')),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='app.booking', verbose_name='Бронирование')),
            ],
            options={
                'verbose_name': 'Заявки на бронирование дома',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Оценка посещения')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('booking', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingReview', to='app.booking')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userReview', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bath_cup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priceCup', to='app.bathcup')),
                ('bath_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priceOption', to='app.bathoption')),
                ('bath_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priceTime', to='app.bathtime')),
                ('home_price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priceHome', to='app.homeprice')),
            ],
            options={
                'verbose_name': 'Стоимость услуг',
            },
        ),
    ]
