# Generated by Django 6.0.5 on 2026-06-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathbooking',
            name='duration',
            field=models.PositiveSmallIntegerField(choices=[(2, '2 часа'), (3, '3 часа'), (4, '4 часа')], null=True, verbose_name='Продолжительность бани'),
        ),
    ]
