# Generated by Django 6.0.5 on 2026-06-03 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_bathbooking_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bath_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bath_booking', to='app.bathbooking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='home_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_booking', to='app.homebooking'),
        ),
    ]
