# Generated by Django 6.0.5 on 2026-06-03 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_booking_bath_booking_booking_home_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bath_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bath_booking', to='app.bathbooking', verbose_name='Бронирование бани'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='home_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_booking', to='app.homebooking', verbose_name='Бронирование дома'),
        ),
    ]
