# Generated by Django 6.0.5 on 2026-06-03 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_booking_bath_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bath_booking',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='home_booking',
        ),
        migrations.AlterField(
            model_name='bathbooking',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bathBookings', to='app.booking', verbose_name='Бронирование'),
        ),
        migrations.AlterField(
            model_name='homebooking',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='app.booking', verbose_name='Бронирование'),
        ),
    ]
