# Generated by Django 6.0.5 on 2026-06-06 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_booking_bath_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathbooking',
            name='steam_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bath_booking', to='app.bathprogram', verbose_name='Программы парения'),
        ),
        migrations.AlterField(
            model_name='homebooking',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_booking', to='app.booking', verbose_name='Бронирование'),
        ),
    ]
