# Generated by Django 6.0.5 on 2026-06-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_bathbooking_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathprogram',
            name='price',
            field=models.IntegerField(default=6000, verbose_name='Стоимость программы'),
        ),
    ]
